package com.yi.pojo;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Onduty {

    private Integer dutyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.doctorid
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private Integer doctorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.week
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.starttime
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private String starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.endtime
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private String endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.limit
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private Integer limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.balance
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onduty.state
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onduty.dutyid
     *
     * @return the value of onduty.dutyid
     *
     * @mbg.generated Tue Nov 24 13:59:44 CST 2020
     */

}